name: pypi

on:
  push:
    tags:
    - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Set version
      env:
        GITHUB_TAG: ${{github.ref}}
      run: |
        python -c "
        import os
        assert os.getenv('GITHUB_TAG').startswith('refs/tags/v')
        version = os.getenv('GITHUB_TAG').replace('refs/tags/v', '')
        with open('django_toosimple_q/__init__.py', 'r') as f:
            contents = f.read()
        with open('django_toosimple_q/__init__.py', 'w') as f:
            f.write(contents.replace('__version__ = \'dev\'', f'__version__ = \'{version}\''))
        "
    - name: Build
      run: python setup.py sdist bdist_wheel
    - name: Assert tag matches version
      env:
        GITHUB_TAG: ${{github.ref}}
      run: |
        python -c "
        import os, django_toosimple_q;
        print('tag : ' + os.getenv('GITHUB_TAG'));
        print('module : ' + django_toosimple_q.__version__);
        assert os.getenv('GITHUB_TAG') == 'refs/tags/v'+django_toosimple_q.__version__, 'Version mismatch'
        "
    - name: Publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: twine upload dist/*
